version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: abisheknanjappa/employeemanagerserver:tagname
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_manager
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: employee_manager
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
